---
- name: install homesick
  command: /usr/local/bin/gem install homesick --no-ri --no-rdoc

- name: clone homesick repos
  command: /usr/local/bin/homesick clone {{item.repo}} creates=/Users/{{ lookup('env','USER') }}/.homesick/repos/{{ item.name }}
  with_items:
    - { repo: "https://github.com/jarias/dotfiles.git", name: dotfiles }
  sudo: false

- name: symlink dotfiles
  command: /usr/local/bin/homesick symlink --force dotfiles
  sudo: false

- name: ensure zshrc presence
  ignore_errors: True
  file: path=~/.zshrc state=touch

- name: add shim to zsh
  lineinfile: dest=~/.zshrc regexp="\.zshrc\.local" line=". ~/.zshrc.local" state=present
