---
#- name: install macvim
#  homebrew: name=macvim install_options="--env-std --override-system-vim --with-lua"

- name: install vim
  homebrew: name=vim install_options=--override-system-vi

- name: create bundle directory
  file: path=~/.vim/bundle state=directory recurse=true

- name: create autoload directory
  file: path=~/.vim/autoload state=directory recurse=true

- name: install pathogen
  command: curl -LSso ~/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim

- name: install vim plugins
  git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.name }}
  with_items:
    - { repo: 'https://github.com/mileszs/ack.vim.git', name: 'ack.tool' }
    - { repo: 'https://github.com/vim-scripts/molokai.git', name: 'molokai.color' }
    - { repo: 'https://github.com/scrooloose/nerdtree.git', name: 'nerdtree.tool' }
    - { repo: 'https://github.com/jeetsukumaran/vim-buffergator.git', name: 'buffergator.tool' }
    - { repo: 'https://github.com/tpope/vim-fugitive.git', name: 'fugitive.tool' }
    - { repo: 'https://github.com/fatih/vim-go.git', name: 'go.lang' }
    - { repo: 'https://github.com/pangloss/vim-javascript.git', name: 'javascript.lang' }
    - { repo: 'https://github.com/mmalecki/vim-node.js.git', name: 'nodejs.lang' }
    - { repo: 'https://github.com/kien/ctrlp.vim.git', name: 'ctrlp.tool' }
    - { repo: 'https://github.com/scrooloose/nerdcommenter.git', name: 'nerdcommenter.tool' }
    - { repo: 'https://github.com/ervandew/supertab.git', name: 'supertab.tool' }
    - { repo: 'https://github.com/Lokaltog/vim-easymotion.git', name: 'easymotion.tool' }
    - { repo: 'https://github.com/tpope/vim-git.git', name: 'git.lang' }
    - { repo: 'https://github.com/tfnico/vim-gradle.git', name: 'gradle.lang' }
    - { repo: 'https://github.com/groenewege/vim-less.git', name: 'less.lang' }
    - { repo: 'https://github.com/bronson/vim-trailing-whitespace.git', name: 'trailing-whitespace.tool' }
    - { repo: 'https://github.com/terryma/vim-multiple-cursors.git', name: 'multiple-cursors.tool' }
    - { repo: 'https://github.com/scrooloose/syntastic.git', name: 'syntastic.tool' }
    - { repo: 'https://github.com/maksimr/vim-jsbeautify.git', name: 'jsbeautify.tool' }
    - { repo: 'https://github.com/tpope/vim-sensible.git', name: 'vim-sensible.config' }
    - { repo: 'https://github.com/majutsushi/tagbar.git', name: 'tagbar.tool' }
    - { repo: 'https://github.com/vim-scripts/ZoomWin.git', name: 'ZoomWin.tool' }

